### ISSUE TITLE
Graves break on server crash

### ISSUE THREAD

**Issue by colbster937** [Legoman99573/GravesX#12]
Whenever the server crashes, all graves will mess up and be able to be seperated. they dont even act like graves in this state
![image](https://github.com/user-attachments/assets/c6113050-387e-4fc6-922a-10a5d078686d)

**Comment by Legoman99573** [comment]
``/graves dump`` and server version.

**Comment by colbster937** [comment]
Dump: https://mclo.gs/xNzkHWQ

Server Version: Purpur 1.17.1

**Comment by Legoman99573** [comment]
Plugin is on 4.9.3.14, which is 3 versions out of date. Latest version is 4.9.3.17

**Comment by colbster937** [comment]
This bug still occurs in the latest version..

**Comment by Legoman99573** [comment]
> This bug still occurs in the latest version..

``/graves dump`` again just to confirm

**Comment by Legoman99573** [comment]
When a hard crash occurs, ``/graves purge`` should remove them. Other than that, there is no way to backup data if the JVM is hanging, which makes creating another thread useless. There is a soft crash state implemented, but that only works if the Server itself is in a crash state.
