### ISSUE TITLE
XP Farming with compass

### ISSUE THREAD

**Issue by daretmavi** [Legoman99573/GravesX#3]
You can Farm XP with the compass.

Steps to reproduce
1 - Place Grindstone near your Bed
2 - Die, e.g. 40-50 block away.
3 - Remove enchantment from your compass on grindstone - you get XPs
4 - Right click with compass - will show you how far is you grave and compass will re-entchant again.
5 - Repeat step 3 and 4 indefinitely

**Comment by Legoman99573** [comment]
Fixed in https://github.com/Legoman99573/GravesX/commit/8eed9ce581629071774bc2af1723ce545f65cb55
