### ISSUE TITLE
[Bug] GravesX Plugin Fails to Handle Player Death Event Correctly

### ISSUE THREAD

**Issue by v4r1n** [Legoman99573/GravesX#32]
### Minecraft Server Version

1.21.1-98-9b1ee0d (MC: 1.21.1)

### `/graves dump` output

https://mclo.gs/RATqPjs

### Summary of the bug

The GravesX plugin, version 4.9.4.1, fails to correctly deduct money based on player rank when a player dies. The plugin is unable to process the event and throws errors related to incorrect formatting patterns.

### Steps to Reproduce

1. Set up a Minecraft server with Velocity as the proxy and PaperMC 1.21.1 on the backend.
2. Install GravesX version 4.9.4.1 and configure rank-based money deductions for player deaths.
3. Have a player of any rank die in the game.
4. Observe the server logs for the error when the PlayerDeathEvent is triggered.

### Expected Result

When a player dies, the plugin should deduct a percentage of the player's money based on their rank without any errors or interruptions. Each rank should have a custom percentage deduction, and this should be handled smoothly by the GravesX plugin.

### Actual Result

Instead of processing the deduction correctly, the plugin throws an error related to DecimalFormat, specifically a `java.lang.IllegalArgumentException` due to a malformed pattern when handling the PlayerDeathEvent. The event does not proceed, and the deduction does not occur as expected.

### Additional Information

This issue seems related to formatting patterns in Java, specifically the DecimalFormat pattern used for handling money deductions. The error occurs on the PlayerDeathEvent, and the stack trace points to a malformed pattern. Logs and server configuration can be provided upon request.

### Version Confirmation

- [X] I confirm that the issue is present in the latest GravesX Spigot Release or Development Builds.
- [X] If I use development builds in a production environment, I am aware that I will not receive support if I lose data.
- [X] If the issue is caused by another fork or Graves 4.9, then I expect to not get support here and my issue will be closed.
- [X] I am not running an outdated version of GravesX when reporting
- [ ] I am not just clicking checkboxes randomly without reading them. If I don't check this, then I did read everything.

**Comment by Legoman99573** [comment]
PluginManager is not supported.
