### ISSUE TITLE
[Feature Request] Player Heads and Obituaries option for them to drop on the ground separate from other items.

### ISSUE THREAD

**Issue by Goinging** [Legoman99573/GravesX#37]
### Is your feature request related to a problem in GravesX? Please describe.

In Gravesx you have the option of setting specific items that drop on the ground when you die instead of going into the grave. You can theoretically put written books and player heads as a part of those lists to make them drop on the ground, but this will make all player heads and written books in a players inventory drop on the ground and not just those that came from the grave. 

### Describe the solution you'd like

Written books and player heads both should have a true-false toggle on whether they drop on the ground or not.

### Describe alternatives you've considered

The main alternative is trying to use the existing config to make obituaries and player heads drop on the ground, but there is no good way of specifying graves player heads and obituaries instead of other player heads and written books.

### Confirmation

- [X] I confirm that the feature request doesn't already exist on the latest version or development build of GravesX.
- [X] If the issue is caused by another fork, then I expect to not get support here and my issue will be closed.
- [ ] I am not just clicking checkboxes randomly without reading them. If I don't check this, then I did read everything.

**Comment by Legoman99573** [comment]
Back from the store, or my break. Implementing.
