### ISSUE TITLE
[Bug] Can wear anything in armor slots

### ISSUE THREAD

**Issue by mizuo-san** [Legoman99573/GravesX#38]
### Minecraft Server Version

1.21.1

### `/graves dump` output

-

### Summary of the bug

[Video Link](https://youtu.be/MKkHc2ww5sA) - Video too big for github
Summary - I can wear anything in armor slots, actually i dont know how to fix it or how to turn off auto-loo, cant find this in config file

### Steps to Reproduce

Kill, place items in armor slots in grave, loot grave by shift + right click

### Expected Result

put expected items in inventory, wear nothing//wear armor

### Actual Result

wearing items in armor slots

### Screenshots

i put video link because video too big for git, if necessary i can compress video to 480p and try again

### Version Confirmation

- [ ] I confirm that the issue is present in the latest GravesX Spigot Release or Development Builds.
- [ ] If I use development builds in a production environment, I am aware that I will not receive support if I lose data.
- [ ] If the issue is caused by another fork or Graves 4.9, then I expect to not get support here and my issue will be closed.
- [ ] I am not running an outdated version of GravesX when reporting
- [ ] If I use any sort of Plugin Manager/Management plugin that I will not receive support. (Plugin Managers causes alot of behavioral issues and causes more problems than it resolves)
- [ ] I am not just clicking checkboxes randomly without reading them. If I don't check this, then I did read everything.

**Comment by Legoman99573** [comment]
Will look into this. Likely will become a config option for the head slot so that we don't interfere with other plugins as some plugins allow putting blocks on the head slot. Also missing graves dump, which is required.
