### ISSUE TITLE
[Bug] graves dissapear and sql problems?

### ISSUE THREAD

**Issue by kingakis2** [Legoman99573/GravesX#39]
### Minecraft Server Version

1.21.1 pufferfish

### `/graves dump` output

https://mclo.gs/OP6bYSv

### Summary of the bug

graves dissapears when using reload or restarting the server and the plugins sends too much errors about sql

### Steps to Reproduce

just install the plugin and try it without making any changes stills the same

### Expected Result

it should work fine and the graves should not dissapear

### Actual Result

i was trying the plugin to put it on my server and when i see the console there was too many errors about sql from graves, i was changing the hologram config and do a /graves reload and my grave just dissapears, later i try with a new one restarting the server and the grave dissapears too

### Screenshots

https://github.com/user-attachments/assets/539d25b9-0fcd-4645-914e-5aaa3946c3ef

### Version Confirmation

- [X] I confirm that the issue is present in the latest GravesX Spigot Release or Development Builds.
- [X] If I use development builds in a production environment, I am aware that I will not receive support if I lose data.
- [X] If the issue is caused by another fork or Graves 4.9, then I expect to not get support here and my issue will be closed.
- [X] I am not running an outdated version of GravesX when reporting
- [X] If I use any sort of Plugin Manager/Management plugin that I will not receive support. (Plugin Managers causes alot of behavioral issues and causes more problems than it resolves)
- [ ] I am not just clicking checkboxes randomly without reading them. If I don't check this, then I did read everything.

**Comment by Legoman99573** [comment]
Easy fix 🫡

**Comment by Legoman99573** [comment]
Let me know if you have the same issue: https://ci.cwhead.dev/job/GravesX/63/artifact/target/GravesX-4.9.4.3.jar

**Comment by kingakis2** [comment]
this appears on that version https://pastebin.com/sgxhC89M and the plugin stop working
