### ISSUE TITLE
Graves are setting to players heads instead of the custom texture skull defined in grave.yml on Spigot 1.21.1

### ISSUE THREAD

**Issue by Cofye** [Legoman99573/GravesX#4]
When I die the grave is not generated correctly, only a skinless player head in the place that cannot be interacted with.

The console sends the following message

[message.txt](https://github.com/user-attachments/files/16999095/message.txt)

**Comment by Legoman99573** [comment]
Test this version and let me know if the same issue occurs
[GravesX-4.9.3.17.zip](https://github.com/user-attachments/files/17000136/GravesX-4.9.3.17.zip)

**Comment by Legoman99573** [comment]
I love spigot sometimes. Will see if I can get it working again as it will eventually get pushed to paper and other forks.

**Comment by Legoman99573** [comment]
Fixed sortof in commit https://github.com/Legoman99573/GravesX/commit/ffbdd7f105a6e7e881c8c9191d5b6cf7e813df3a. Keeping this opened as there is likely a way to resolve it.

**Comment by Legoman99573** [comment]
Resolved in https://github.com/Legoman99573/GravesX/commit/29a0244e77f9df6b38f66ca06f65e68cb8db7937
