### ISSUE TITLE
[Feature Request] Check player balance before grave teleport warmup, not after.

### ISSUE THREAD

**Issue by Pookachu** [Legoman99573/GravesX#56]
### Is your feature request related to a problem in GravesX? Please describe.

Graves should check for a player not having enough money before they start the teleport warmup period, not right as it's trying to teleport them.

### Describe the solution you'd like

Check the player balance and cancel the teleport warmup period if it's not enough.

### Confirmation

- [X] I confirm that the feature request doesn't already exist on the latest version or development build of GravesX.
- [X] If the issue is caused by another fork, then I expect to not get support here and my issue will be closed.
- [ ] I am not just clicking checkboxes randomly without reading them. If I don't check this, then I did read everything.

**Comment by Legoman99573** [comment]
More of a bug than a feature. Easy Fix.
