### ISSUE TITLE
[Bug] Death in flowing water - DB corruption

### ISSUE THREAD

**Issue by daretmavi** [Legoman99573/GravesX#60]
### Minecraft Server Version

paper-1.21.1-128

### `/graves dump` output

https://mclo.gs/56KC8Qi

### Summary of the bug

If player dies in flowing water, then after server restart, the grave is missing data

In console you get warning like this:
` WARN]: [GravesX] Data is missing or invalid in result set for location: Location{world=CraftWorld{name=world},x=364.0,y=-35.0,z=895.0,pitch=0.0,yaw=0.0}`

### Steps to Reproduce

1. E.g. let flow water from top
2. Stay under the flowing water and let your self kill by moster
3. Go back to the grave - you can open it and take some stuff
4. Log out
5. Stop and Start server again
6. You get the "Data is missing" warning and the grave is not accessible anymore
7. In the DB / block is for this location `replace_material` and `replace_data` =`NULL`
8. Grave is not accessible anymore

### Expected Result

Grave should be ok, even in flowing water

### Actual Result

Grave is lost

If I change the DB `replace_material=WATER` and `replace_data=minecraft:water[level=0]` the the grave is good again

### Version Confirmation

- [X] I confirm that the issue is present in the latest GravesX Spigot Release or Development Builds.
- [X] If I use development builds in a production environment, I am aware that I will not receive support if I lose data.
- [X] If the issue is caused by another fork or Graves 4.9, then I expect to not get support here and my issue will be closed.
- [X] I am not running an outdated version of GravesX when reporting
- [X] If I use any sort of Plugin Manager/Management plugin that I will not receive support. (Plugin Managers causes alot of behavioral issues and causes more problems than it resolves)
- [ ] I am not just clicking checkboxes randomly without reading them. If I don't check this, then I did read everything.

**Comment by Legoman99573** [comment]
Fixed in https://github.com/Legoman99573/GravesX/commit/f2914f4696f7a2e634640be80250232dbf82de64
