### ISSUE TITLE
[Bug] What is with the dozens of libraries that GravesX loads?

### ISSUE THREAD

**Issue by TerdyTheTerd** [Legoman99573/GravesX#80]
### Minecraft Server Version

1.21.3

### `/graves dump` output

Not providing this info

### Summary of the bug

This plugin loads dozens on unnecessary libraries. Its loading in tons of libraries related to authentication, cloud services like AWS and connections like http clients and SSL. None of this is needed for a graves plugin, so what gives?

### Steps to Reproduce

Install the plugin, check the console. Also checking the source code there is clearly something fishy going on, with a separate jar needing to be installed for auth?

### Expected Result

I suspect there is something fishy going on here, but I don't have the time to dig into it.

### Actual Result

A plugin that only loads what is actually needed.

### Version Confirmation

- [X] I confirm that the issue is present in the latest GravesX Spigot Release or Development Builds.
- [X] If I use development builds in a production environment, I am aware that I will not receive support if I lose data.
- [X] If the issue is caused by another fork or Graves 4.9, then I expect to not get support here and my issue will be closed.
- [X] I am not running an outdated version of GravesX when reporting
- [X] If I use any sort of Plugin Manager/Management plugin that I will not receive support. (Plugin Managers causes alot of behavioral issues and causes more problems than it resolves)
- [ ] I am not just clicking checkboxes randomly without reading them. If I don't check this, then I did read everything.

**Comment by Legoman99573** [comment]
I assume you are speaking of this line:
https://github.com/Legoman99573/GravesX/blob/4f1717a65a1db0c30ec9a69aa96a27a324b2abdd/src/main/java/com/ranull/graves/Graves.java#L221

**Comment by Legoman99573** [comment]
I can work on not loading database libraries if they aren't required.

**Comment by TerdyTheTerd** [comment]
No, I was talking about these. You cannot expect me to believe that a MC plugin requires all of these libraries for AWS services, HTTP clients, SSL drivers for Linux, Macintosh and Windows. There are 227 libraries that get loaded in here, that is beyond unreasonable.
[GravesX] Loading library com.zaxxer.HikariCP version 6.0.0.
[GravesX] Loading library com.zaxxer:HikariCP:6.0.0
[GravesX] Loading library org.slf4j:slf4j-api:1.7.36
[GravesX] Loading library org.javassist:javassist:3.29.2-GA
[GravesX] Loading library io.micrometer:micrometer-core:1.5.10
[GravesX] Loading library org.hdrhistogram:HdrHistogram:2.1.12
[GravesX] Loading library org.latencyutils:LatencyUtils:2.0.3
[GravesX] Loaded library com.zaxxer.HikariCP version 6.0.0 and shaded successfully.
[GravesX] Loading library org.xerial.sqlite-jdbc version 3.47.0.0.
[GravesX] Loading library org.xerial:sqlite-jdbc:3.47.0.0
[GravesX] Loading library org.slf4j:slf4j-api:1.7.36
[GravesX] Loaded library org.xerial.sqlite-jdbc version 3.47.0.0 successfully.
[GravesX] Loading library org.json.json version 20240303.
[GravesX] Loading library org.json:json:20240303
[GravesX] Loaded library org.json.json version 20240303 successfully.
[GravesX] Loading library org.postgresql.postgresql version 42.7.4.
[GravesX] Loading library org.postgresql:postgresql:42.7.4
[GravesX] Loading library org.checkerframework:checker-qual:3.42.0
[GravesX] Loading library junit:junit:4.13.2
[GravesX] Loading library org.hamcrest:hamcrest-core:1.3
[GravesX] Loading library org.junit.jupiter:junit-jupiter-api:5.10.2
[GravesX] Loading library org.opentest4j:opentest4j:1.3.0
[GravesX] Loading library org.junit.platform:junit-platform-commons:1.10.2
[GravesX] Loading library org.apiguardian:apiguardian-api:1.1.2
[GravesX] Loading library org.junit.jupiter:junit-jupiter-engine:5.10.2
[GravesX] Loading library org.junit.platform:junit-platform-engine:1.10.2
[GravesX] Loading library com.github.waffle:waffle-jna:1.9.1
[GravesX] Loading library net.java.dev.jna:jna:4.5.1
[GravesX] Loading library net.java.dev.jna:jna-platform:4.5.1
[GravesX] Loading library org.slf4j:jcl-over-slf4j:1.7.25
[GravesX] Loading library org.slf4j:slf4j-api:1.7.25
[GravesX] Loading library com.github.ben-manes.caffeine:caffeine:2.6.2
[GravesX] Loaded library org.postgresql.postgresql version 42.7.4 and shaded successfully.
[GravesX] Loading library org.mariadb.jdbc.mariadb-java-client version 3.5.0.
[GravesX] Loading library org.mariadb.jdbc:mariadb-java-client:3.5.0
[GravesX] Loading library com.github.waffle:waffle-jna:3.3.0
[GravesX] Loading library net.java.dev.jna:jna:5.13.0
[GravesX] Loading library net.java.dev.jna:jna-platform:5.13.0
[GravesX] Loading library org.slf4j:jcl-over-slf4j:2.0.7
[GravesX] Loading library com.github.ben-manes.caffeine:caffeine:2.9.3
[GravesX] Loading library com.google.errorprone:error_prone_annotations:2.10.0
[GravesX] Loading library org.checkerframework:checker-qual:3.32.0
[GravesX] Loading library org.slf4j:slf4j-api:2.0.3
[GravesX] Loading library software.amazon.awssdk:rds:2.21.1
[GravesX] Loading library software.amazon.awssdk:aws-query-protocol:2.21.1
[GravesX] Loading library software.amazon.awssdk:protocol-core:2.21.1
[GravesX] Loading library software.amazon.awssdk:profiles:2.21.1
[GravesX] Loading library software.amazon.awssdk:http-auth-aws:2.21.1
[GravesX] Loading library software.amazon.awssdk:checksums-spi:2.21.1
[GravesX] Loading library software.amazon.awssdk:checksums:2.21.1
[GravesX] Loading library software.amazon.awssdk:sdk-core:2.21.1
[GravesX] Loading library org.reactivestreams:reactive-streams:1.0.4
[GravesX] Loading library software.amazon.awssdk:auth:2.21.1
[GravesX] Loading library software.amazon.eventstream:eventstream:1.0.1
[GravesX] Loading library software.amazon.awssdk:http-auth-spi:2.21.1
[GravesX] Loading library software.amazon.awssdk:http-auth:2.21.1
[GravesX] Loading library software.amazon.awssdk:identity-spi:2.21.1
[GravesX] Loading library software.amazon.awssdk:http-client-spi:2.21.1
[GravesX] Loading library software.amazon.awssdk:regions:2.21.1
[GravesX] Loading library software.amazon.awssdk:annotations:2.21.1
[GravesX] Loading library software.amazon.awssdk:utils:2.21.1
[GravesX] Loading library software.amazon.awssdk:aws-core:2.21.1
[GravesX] Loading library software.amazon.awssdk:metrics-spi:2.21.1
[GravesX] Loading library software.amazon.awssdk:json-utils:2.21.1
[GravesX] Loading library software.amazon.awssdk:third-party-jackson-core:2.21.1
[GravesX] Loading library software.amazon.awssdk:endpoints-spi:2.21.1
[GravesX] Loading library software.amazon.awssdk:apache-client:2.21.1
[GravesX] Loading library org.apache.httpcomponents:httpclient:4.5.13
[GravesX] Loading library commons-logging:commons-logging:1.2
[GravesX] Loading library org.apache.httpcomponents:httpcore:4.4.13
[GravesX] Loading library commons-codec:commons-codec:1.15
[GravesX] Loading library software.amazon.awssdk:netty-nio-client:2.21.1
[GravesX] Loading library io.netty:netty-codec-http:4.1.94.Final
[GravesX] Loading library io.netty:netty-codec-http2:4.1.94.Final
[GravesX] Loading library io.netty:netty-codec:4.1.94.Final
[GravesX] Loading library io.netty:netty-transport:4.1.94.Final
[GravesX] Loading library io.netty:netty-common:4.1.94.Final
[GravesX] Loading library io.netty:netty-buffer:4.1.94.Final
[GravesX] Loading library io.netty:netty-handler:4.1.94.Final
[GravesX] Loading library io.netty:netty-transport-native-unix-common:4.1.94.Final
[GravesX] Loading library io.netty:netty-transport-classes-epoll:4.1.94.Final
[GravesX] Loading library io.netty:netty-resolver:4.1.94.Final
[GravesX] Loaded library org.mariadb.jdbc.mariadb-java-client version 3.5.0 and shaded successfully.
[GravesX] Loading library com.mysql.mysql-connector-j version 9.1.0.
[GravesX] Loading library com.mysql:mysql-connector-j:9.1.0
[GravesX] Loading library com.google.protobuf:protobuf-java:4.26.1
[GravesX] Loading library com.oracle.oci.sdk:oci-java-sdk-common:3.41.2
[GravesX] Loading library com.fasterxml.jackson.core:jackson-annotations:2.15.2
[GravesX] Loading library com.fasterxml.jackson.core:jackson-databind:2.13.4.2
[GravesX] Loading library org.bouncycastle:bcpkix-jdk15to18:1.74
[GravesX] Loading library org.bouncycastle:bcutil-jdk15to18:1.74
[GravesX] Loading library org.bouncycastle:bcprov-jdk15to18:1.74
[GravesX] Loading library com.oracle.oci.sdk:oci-java-sdk-circuitbreaker:3.41.2
[GravesX] Loading library io.github.resilience4j:resilience4j-circuitbreaker:1.7.1
[GravesX] Loading library io.vavr:vavr:0.10.2
[GravesX] Loading library io.vavr:vavr-match:0.10.2
[GravesX] Loading library io.github.resilience4j:resilience4j-core:1.7.1
[GravesX] Loading library com.oracle.oci.sdk:oci-java-sdk-common-httpclient:3.41.2
[GravesX] Loading library jakarta.annotation:jakarta.annotation-api:2.1.1
[GravesX] Loading library org.slf4j:slf4j-api:1.7.33
[GravesX] Loaded library com.mysql.mysql-connector-j version 9.1.0 and shaded successfully.
[GravesX] Loading library com.h2database.h2 version 2.3.232.
[GravesX] Loading library com.h2database:h2:2.3.232
[GravesX] Loaded library com.h2database.h2 version 2.3.232 and shaded successfully.
[GravesX] Loading library net.kyori.adventure-api version 4.17.0.
[GravesX] Loading library net.kyori:adventure-api:4.17.0
[GravesX] Loading library net.kyori:adventure-key:4.17.0
[GravesX] Loading library net.kyori:examination-api:1.3.0
[GravesX] Loading library net.kyori:examination-string:1.3.0
[GravesX] Loading library org.jetbrains:annotations:24.1.0
[GravesX] Loaded library net.kyori.adventure-api version 4.17.0 and shaded successfully.
[GravesX] Loading library net.kyori.adventure-text-minimessage version 4.17.0.
[GravesX] Loading library net.kyori:adventure-text-minimessage:4.17.0
[GravesX] Loading library net.kyori:adventure-api:4.17.0
[GravesX] Loading library net.kyori:adventure-key:4.17.0
[GravesX] Loading library net.kyori:examination-api:1.3.0
[GravesX] Loading library net.kyori:examination-string:1.3.0
[GravesX] Loading library org.jetbrains:annotations:24.1.0
[GravesX] Loaded library net.kyori.adventure-text-minimessage version 4.17.0 and shaded successfully.
[GravesX] Loading library net.kyori.adventure-text-serializer-gson version 4.17.0.
[GravesX] Loading library net.kyori:adventure-text-serializer-gson:4.17.0
[GravesX] Loading library net.kyori:adventure-text-serializer-json:4.17.0
[GravesX] Loading library net.kyori:adventure-api:4.17.0
[GravesX] Loading library net.kyori:adventure-key:4.17.0
[GravesX] Loading library net.kyori:examination-api:1.3.0
[GravesX] Loading library net.kyori:examination-string:1.3.0
[GravesX] Loading library org.jetbrains:annotations:24.1.0
[GravesX] Loading library net.kyori:option:1.0.0
[GravesX] Loading library com.google.code.gson:gson:2.8.0
[GravesX] Loading library com.google.auto.service:auto-service-annotations:1.1.1
[GravesX] Loaded library net.kyori.adventure-text-serializer-gson version 4.17.0 and shaded successfully.
[GravesX] Loading library net.kyori.adventure-platform-bukkit version 4.3.3.
[GravesX] Loading library net.kyori:adventure-platform-bukkit:4.3.3
[GravesX] Loading library net.kyori:adventure-platform-api:4.3.3
[GravesX] Loading library net.kyori:adventure-api:4.13.1
[GravesX] Loading library net.kyori:adventure-key:4.13.1
[GravesX] Loading library net.kyori:adventure-text-serializer-bungeecord:4.3.3
[GravesX] Loading library net.kyori:adventure-text-serializer-legacy:4.13.1
[GravesX] Loading library net.kyori:adventure-nbt:4.13.1
[GravesX] Loading library net.kyori:examination-api:1.3.0
[GravesX] Loading library net.kyori:examination-string:1.3.0
[GravesX] Loading library org.jetbrains:annotations:24.0.1
[GravesX] Loading library net.kyori:adventure-text-serializer-gson:4.13.1
[GravesX] Loading library net.kyori:adventure-text-serializer-gson-legacy-impl:4.13.1
[GravesX] Loading library net.kyori:adventure-platform-facet:4.3.3
[GravesX] Loading library net.kyori:adventure-platform-viaversion:4.3.3
[GravesX] Loaded library net.kyori.adventure-platform-bukkit version 4.3.3 and shaded successfully.
[GravesX] Loading library de.themoep.minedown-adventure version 1.7.3-graves.
[GravesX] Loading library de.themoep:minedown-adventure:1.7.3-graves
[GravesX] Loaded library de.themoep.minedown-adventure version 1.7.3-graves and shaded successfully.
[GravesX] Loading library me.imdanix.MiniTranslator version 2.1-graves.
[GravesX] Loading library me.imdanix:MiniTranslator:2.1-graves
[GravesX] Loaded library me.imdanix.MiniTranslator version 2.1-graves and shaded successfully.
[GravesX] Loading library com.github.puregero.multilib version 1.2.4.
[GravesX] Loading library com.github.puregero:multilib:1.2.4
[GravesX] Loading library org.jetbrains:annotations:22.0.0
[GravesX] Loading library com.github.puregero:multilib-common:1.2.4
[GravesX] Loading library com.github.puregero:multilib-bukkit:1.2.4
[GravesX] Loading library com.github.puregero:multilib-multipaper:1.2.4
[GravesX] Loading library com.github.puregero:regionized-common:1.2.4
[GravesX] Loading library com.github.puregero:regionized-bukkit:1.2.4
[GravesX] Loading library com.github.puregero:regionized-paper:1.2.4
[GravesX] Loaded library com.github.puregero.multilib version 1.2.4 and shaded successfully.
[GravesX] Loading library org.apache.commons.commons-text version 1.12.0.
[GravesX] Loading library org.apache.commons:commons-text:1.12.0
[GravesX] Loading library org.apache.commons:commons-lang3:3.14.0
[GravesX] Loaded library org.apache.commons.commons-text version 1.12.0 and shaded successfully.
[GravesX] Loading library com.microsoft.sqlserver.mssql-jdbc version 12.8.1.jre11.
[GravesX] Loading library com.microsoft.sqlserver:mssql-jdbc:12.8.1.jre11
[GravesX] Loading library com.azure:azure-security-keyvault-keys:4.7.3
[GravesX] Loading library com.azure:azure-core:1.45.1
[GravesX] Loading library com.fasterxml.jackson.core:jackson-annotations:2.13.5
[GravesX] Loading library com.fasterxml.jackson.core:jackson-core:2.13.5
[GravesX] Loading library com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.5
[GravesX] Loading library io.projectreactor:reactor-core:3.4.34
[GravesX] Loading library org.reactivestreams:reactive-streams:1.0.4
[GravesX] Loading library com.azure:azure-core-http-netty:1.13.11
[GravesX] Loading library io.netty:netty-handler:4.1.101.Final
[GravesX] Loading library io.netty:netty-resolver:4.1.101.Final
[GravesX] Loading library io.netty:netty-transport:4.1.101.Final
[GravesX] Loading library io.netty:netty-handler-proxy:4.1.101.Final
[GravesX] Loading library io.netty:netty-codec-socks:4.1.101.Final
[GravesX] Loading library io.netty:netty-buffer:4.1.101.Final
[GravesX] Loading library io.netty:netty-codec:4.1.101.Final
[GravesX] Loading library io.netty:netty-codec-http:4.1.101.Final
[GravesX] Loading library io.netty:netty-codec-http2:4.1.101.Final
[GravesX] Loading library io.netty:netty-transport-native-unix-common:4.1.101.Final
[GravesX] Loading library io.netty:netty-transport-native-epoll:4.1.101.Final:linux-x86_64
[GravesX] Loading library io.netty:netty-transport-classes-epoll:4.1.101.Final
[GravesX] Loading library io.netty:netty-transport-native-kqueue:4.1.101.Final:osx-x86_64
[GravesX] Loading library io.netty:netty-transport-classes-kqueue:4.1.101.Final
[GravesX] Loading library io.netty:netty-tcnative-boringssl-static:2.0.62.Final
[GravesX] Loading library io.netty:netty-tcnative-classes:2.0.62.Final
[GravesX] Loading library io.netty:netty-tcnative-boringssl-static:2.0.62.Final:linux-x86_64
[GravesX] Loading library io.netty:netty-tcnative-boringssl-static:2.0.62.Final:linux-aarch_64
[GravesX] Loading library io.netty:netty-tcnative-boringssl-static:2.0.62.Final:osx-x86_64
[GravesX] Loading library io.netty:netty-tcnative-boringssl-static:2.0.62.Final:osx-aarch_64
[GravesX] Loading library io.netty:netty-tcnative-boringssl-static:2.0.62.Final:windows-x86_64
[GravesX] Loading library io.projectreactor.netty:reactor-netty-http:1.0.39
[GravesX] Loading library io.netty:netty-resolver-dns:4.1.101.Final
[GravesX] Loading library io.netty:netty-codec-dns:4.1.101.Final
[GravesX] Loading library io.netty:netty-resolver-dns-native-macos:4.1.101.Final:osx-x86_64
[GravesX] Loading library io.netty:netty-resolver-dns-classes-macos:4.1.101.Final
[GravesX] Loading library io.projectreactor.netty:reactor-netty-core:1.0.39
[GravesX] Loading library io.netty:netty-common:4.1.101.Final
[GravesX] Loading library com.azure:azure-identity:1.12.2
[GravesX] Loading library com.azure:azure-json:1.1.0
[GravesX] Loading library com.microsoft.azure:msal4j-persistence-extension:1.3.0
[GravesX] Loading library net.java.dev.jna:jna:5.13.0
[GravesX] Loading library net.java.dev.jna:jna-platform:5.6.0
[GravesX] Loading library com.microsoft.azure:msal4j:1.15.1
[GravesX] Loading library com.nimbusds:oauth2-oidc-sdk:11.9.1
[GravesX] Loading library com.github.stephenc.jcip:jcip-annotations:1.0-1
[GravesX] Loading library com.nimbusds:content-type:2.3
[GravesX] Loading library com.nimbusds:lang-tag:1.7
[GravesX] Loading library com.nimbusds:nimbus-jose-jwt:9.37.3
[GravesX] Loading library net.minidev:json-smart:2.5.0
[GravesX] Loading library net.minidev:accessors-smart:2.5.0
[GravesX] Loading library org.ow2.asm:asm:9.3
[GravesX] Loading library org.slf4j:slf4j-api:1.7.36
[GravesX] Loading library com.fasterxml.jackson.core:jackson-databind:2.13.4.2
[GravesX] Loading library org.antlr:antlr4-runtime:4.9.3
[GravesX] Loading library com.google.code.gson:gson:2.10.1
[GravesX] Loading library org.bouncycastle:bcprov-jdk18on:1.78
[GravesX] Loading library org.bouncycastle:bcpkix-jdk18on:1.78
[GravesX] Loading library org.bouncycastle:bcutil-jdk18on:1.78
[GravesX] Loaded library com.microsoft.sqlserver.mssql-jdbc version 12.8.1.jre11 and shaded successfully.

**Comment by xsmeths** [comment]
the awssdk is a bundled part of the mariadb library which is used for handling of that particular database type, I hope this clears up any confusion over why these are loaded/needed
